[package]
name = "krossbar-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive", "color"] }
log = "0.4"
tokio = { version = "1.20", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "signal",
] }
chrono = "0.4"

krossbar-bus-lib = "0.5.6"
krossbar-log-common = "0.5.0"

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.19", features = ["fs", "signal"] }
