[package]
name = "krossbar-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive", "color"] }
log = "0.4"
tokio = { version = "1.20", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "signal",
] }
chrono = "0.4"

krossbar-bus-lib = { git = "https://github.com/krossbar-platform/krossbar-bus.git" }

krossbar-log-common = { path = "../krossbar-log-common" }
krossbar-log-lib = { path = "../krossbar-log-lib" }

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.19", features = ["fs", "signal"] }

krossbar-bus-hub = { git = "https://github.com/krossbar-platform/krossbar-bus.git" }
