[package]
name = "krossbar-log-common"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
