[package]
name = "karo-log-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive", "color"] }
log = "0.4"

karo-log-common = { path = "../karo-log-common" }
karo-log-lib = { path = "../karo-log-lib" }
