[package]
name = "krossbar-log-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1"
log = { version = "0.4", features = ["std", "release_max_level_debug"] }
tokio = { version = "1.38", features = ["net", "time"] }

krossbar-bus-common = "0.5.0"
krossbar-common-rpc = "0.5.6"
krossbar-log-common = "0.5.1"

[dev-dependencies]
tokio = { version = "1.38", features = ["full"] }
